### ISSUE TITLE
Soft realtime loop file got converted to space indentations instead of tabs. 

### ISSUE THREAD

**Issue by tkevinbest** [UM-LoCoLab/NeuroLocoMiddleware#14]
Switch soft realtime loop code back to tab indentation to allow merges with OSL library.

**Comment by tkevinbest** [comment]
Or maybe not tabs, but right now it is only two spaces...

**Comment by tkevinbest** [comment]
@jmontp can you give an estimated timeline for this? We have to do this before merging with OSL lib.

**Comment by jmontp** [comment]
Created a new branch and pull request here 

https://github.com/UM-LoCoLab/NeuroLocoMiddleware/pull/16

**Comment by tkevinbest** [comment]
Resolved
